image: electronuserland/electron-builder:latest

build_assets:
  stage: build
  script:
    - yarn install
    - yarn run build
    - tar -czvf build.tar.gz build/
  artifacts:
    paths:
      - build/docker-explorer_0.0.0_amd64.deb
    expire_in: 1 week