image: electronuserland/electron-builder:latest

build_assets:
  stage: build
  script:
    - yarn install
    - yarn run build
    - ls -la build/
  artifacts:
    paths:
      - build/
    expire_in: 1 week