image: electronuserland/electron-builder:latest

build_assets:
  stage: build
  script:
    - yarn install
    - yarn run build
    - tar -czvf build.tar.gz build/docker-explorer*
    - ls -lah build.tar.gz
  artifacts:
    paths:
      - build.tar.gz
    expire_in: 1 week